package com.njust.smsmanager.dbUtils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.njust.smsmanager.dbUtils.Groups;
import com.njust.smsmanager.dbUtils.ThreadGroups;

import com.njust.smsmanager.dbUtils.GroupsDao;
import com.njust.smsmanager.dbUtils.ThreadGroupsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupsDaoConfig;
    private final DaoConfig threadGroupsDaoConfig;

    private final GroupsDao groupsDao;
    private final ThreadGroupsDao threadGroupsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        threadGroupsDaoConfig = daoConfigMap.get(ThreadGroupsDao.class).clone();
        threadGroupsDaoConfig.initIdentityScope(type);

        groupsDao = new GroupsDao(groupsDaoConfig, this);
        threadGroupsDao = new ThreadGroupsDao(threadGroupsDaoConfig, this);

        registerDao(Groups.class, groupsDao);
        registerDao(ThreadGroups.class, threadGroupsDao);
    }
    
    public void clear() {
        groupsDaoConfig.clearIdentityScope();
        threadGroupsDaoConfig.clearIdentityScope();
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

    public ThreadGroupsDao getThreadGroupsDao() {
        return threadGroupsDao;
    }

}
