package com.njust.smsmanager.dbUtils;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "THREAD_GROUPS".
*/
public class ThreadGroupsDao extends AbstractDao<ThreadGroups, Long> {

    public static final String TABLENAME = "THREAD_GROUPS";

    /**
     * Properties of entity ThreadGroups.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Thread_id = new Property(1, Long.class, "thread_id", false, "thread_id");
        public final static Property Group_id = new Property(2, Long.class, "group_id", false, "group_id");
    }

    private DaoSession daoSession;


    public ThreadGroupsDao(DaoConfig config) {
        super(config);
    }
    
    public ThreadGroupsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"THREAD_GROUPS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"thread_id\" INTEGER," + // 1: thread_id
                "\"group_id\" INTEGER);"); // 2: group_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"THREAD_GROUPS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ThreadGroups entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long thread_id = entity.getThread_id();
        if (thread_id != null) {
            stmt.bindLong(2, thread_id);
        }
 
        Long group_id = entity.getGroup_id();
        if (group_id != null) {
            stmt.bindLong(3, group_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ThreadGroups entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long thread_id = entity.getThread_id();
        if (thread_id != null) {
            stmt.bindLong(2, thread_id);
        }
 
        Long group_id = entity.getGroup_id();
        if (group_id != null) {
            stmt.bindLong(3, group_id);
        }
    }

    @Override
    protected final void attachEntity(ThreadGroups entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ThreadGroups readEntity(Cursor cursor, int offset) {
        ThreadGroups entity = new ThreadGroups( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // thread_id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // group_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ThreadGroups entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThread_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setGroup_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ThreadGroups entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ThreadGroups entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ThreadGroups entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGroupsDao().getAllColumns());
            builder.append(" FROM THREAD_GROUPS T");
            builder.append(" LEFT JOIN GROUPS T0 ON T.\"group_id\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ThreadGroups loadCurrentDeep(Cursor cursor, boolean lock) {
        ThreadGroups entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Groups groups = loadCurrentOther(daoSession.getGroupsDao(), cursor, offset);
        entity.setGroups(groups);

        return entity;    
    }

    public ThreadGroups loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ThreadGroups> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ThreadGroups> list = new ArrayList<ThreadGroups>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ThreadGroups> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ThreadGroups> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
